### ISSUE TITLE
continue from where left

### ISSUE THREAD

**Issue by SpidermanArda** [voicemxil/TS2-Starter-Pack#50]
it would be really awesome if the installer checked for any already installed files before starting installation.

**Comment by voicemxil** [comment]
The installer already checks for existing files, and continues downloads for any temp files that were stopped. 
Installing over existing/unfinished files could potentially cause issues, which is why it prompts to remove them before installing. If you want to just reinstall the registry keys and fixes you can do that with the Standalone Installer, otherwise with the Web Installer it's a clean install.
