### ISSUE TITLE
Store/Pre-order Content not included with Standalone Installer (more feature parity for offline installer)

### ISSUE THREAD

**Issue by Akoi89** [voicemxil/TS2-Starter-Pack#54]
Please add Store/Pre-order Content to the Standalone like it is on the web installer.

Also any chance you could also add "Localized Music Unlocked by spockthewok" to it as well for more feature parity? 

Mainly I just want more feature parity between the online/offline versions for archival reasons/offline installation.

Thanks! (love what you have done here to give us the perfect sims 2 installer)

**Comment by voicemxil** [comment]
Including this extra content in the standalone installer would increase the executable file sizes by almost 7x, and isn't very feasible as the standalone version is mainly just for touchup + fixes and doesn't include any game files.

Fortunately these are both easy to install separately. In terms of the store content, all you have to do is extract it to the Downloads folder. I can merge it all together into a single archive and add it into the same release with the game packs so that they're at least together. The localized music mod is found either on ModTheSims or in the components folder of the repository.

PS I would always recommend using the latest version rather than old archived ones.

**Comment by Akoi89** [comment]
I wasn't asking you to include it in the .exe file, was just asking for it to be included in the TS2 Archives/having the installer let you install them when it detects the files there.

I was using the files from the "TS2 Archives v13.2" I assume that's the latest?

**Comment by voicemxil** [comment]
> I wasn't asking you to include it in the .exe file, was just asking for it to be included in the TS2 Archives/having the installer let you install them when it detects the files there. (I see its in components/Store_Content)
> 
> I was using the files from the "TS2 Archives v13.2" I assume that's the latest?

v12 is the latest, 13.2 is the cleanup script version.
And I can add that

**Comment by Akoi89** [comment]
thanks for that!
Uh oh... I've been using the 13.2 pack myself... is there any real reason not to use it?

**Comment by voicemxil** [comment]
> thanks for that! Uh oh... I've been using the 13.2 pack myself... is there any real reason not to use it?

only if you hate that a couple items show up as a newer pack than they originally did
