### ISSUE TITLE
Don't install Shadow fix is DXVK is installed

### ISSUE THREAD

**Issue by tannisroot** [voicemxil/TS2-Starter-Pack#8]
DXVK has a built-in workaround that allows Sims 2 shadows to render normally. Simnopke's shadow fix is not needed when it's installed and rather makes shadows look worse

**Comment by voicemxil** [comment]
Yes, I am aware of how the two interact. Users are not forced to install the shadow fix, it is a selectable option.

**Comment by tannisroot** [comment]
It's just that vast majority are not aware and will proceed with installing both, which as I've mentioned is undesirable

**Comment by voicemxil** [comment]
This has been in the guide since the beginning. It will still be a selectable option either way.

**Comment by voicemxil** [comment]
> It's just that vast majority are not aware

The vast majority are not even using DXVK. For Windows user, it's a last resort.

The guide does mention that the shadow fix is redundant for DXVK users, and also doesn't recommend DXVK for Windows by default.

For some Windows users, DXVK actually worsens the flashing/issues. I advise users to uncheck it and only install it afterwards _if_ they have the issues it can help with. In the next release it will be unchecked by default and only accessible for a custom installation type.

The shadow fix checkbox only opens the download page in its current state. It doesn't actually install it automatically since there are 6 different versions.

If you don't read the guide or documentation, you obviously won't know this, but that's not a majority of users.
